name: "Autoloader"

on:
  push:
    paths-ignore:
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'doc/**'

permissions:
  contents: read

jobs:
  tests:
    name: "Autoloader"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Install Composer dependencies"
        run: "composer config platform --unset && composer install"

      - name: "Dump autoloader in the test directory using latest Composer"
        run: "./bin/composer install -d tests/Composer/Test/Autoload/MinimumVersionSupport"

      - name: "Install oldest supported PHP version for autoloader"
        uses: shivammathur/setup-php@2282b6a082fc605c8320908a4cca3a5d1ca6c6fe # 2.35.1
        with:
          coverage: "none"
          extensions: "intl, zip"
          ini-values: "memory_limit=-1"
          php-version: "5.6"

      - name: "Check the autoloader can be executed"
        run: "php main.php"
        working-directory: tests/Composer/Test/Autoload/MinimumVersionSupport
