name: "PHP Lint"

on:
  push:
    paths-ignore:
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'doc/**'

permissions:
  contents: read

jobs:
  tests:
    name: "Lint"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "7.2"
          - "nightly"

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: shivammathur/setup-php@2282b6a082fc605c8320908a4cca3a5d1ca6c6fe # 2.35.1
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none

      - uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520 # 3.1.1
        with:
          dependency-versions: highest

      - name: "Lint PHP files"
        run: |
          hasErrors=0
          for f in $(find src/ tests/ -type f -name '*.php' ! -path '*/vendor/*')
          do
            { error="$(php -derror_reporting=-1 -ddisplay_errors=1 -l -f $f 2>&1 1>&3 3>&-)"; } 3>&1;
            if [ "$error" != "" ]; then
              while IFS= read -r line; do echo "::error file=$f::$line"; done <<< "$error"
              hasErrors=1
            fi
          done
          if [ $hasErrors -eq 1 ]; then
            exit 1
          fi
